server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.58.124:3306/db_pet_store?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: qfjava
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:com/qf/pet/mapper/xml/*.xml




